### ISSUE TITLE
API Transaction เสียครับ

### ISSUE THREAD

**Issue by gunnrcrakr** [maythiwat/WalletAPI#2]
{"code":"MAG-501","data":null,"title":"ปรับปรุงระบบชั่วคราว","message":"บริการนี้อยู่ในระหว่างการปรับปรุงชั่วคราว ขออภัยในความไม่สะดวก","developer_message":"This feature is not available."}

**Comment by maythiwat** [comment]
แก้ไขเรียบร้อยครับ
