### ISSUE TITLE
ตัดบัตรทรูมันนี่

### ISSUE THREAD

**Issue by recycie** [maythiwat/WalletAPI#4]
ตัดบัตรทรูมันนี่ ถ้าเติมผิดเยอะๆ พอจะมีแนวทางไม่ให้โดนบล็อคไหม

**Comment by maythiwat** [comment]
ถ้าใช้ในเว็บขายของขอแนะนำให้ "แบน" user ชั่วคราวดูครับ ซัก 5 นาที 10 นาทีก็ว่าไป
น่าจะช่วยได้อยู่
